<?php

namespace TrajetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends EntityRepository
{
}
