<?php

namespace TrajetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrajetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetsRepository extends EntityRepository
{
}
