home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Default:index }


home_vue10:
    path:     /vue10
    defaults: { _controller: HomeBundle:Default:vue10 }

rando10k1:
    path:     /rando10k1
    defaults: { _controller: HomeBundle:Rando:rando10k1 }
    
home_vue20:
    path:     /vue20
    defaults: { _controller: HomeBundle:Default:vue20 }

home_vue30:
    path:     /vue30
    defaults: { _controller: HomeBundle:Default:vue30 }


home_vue40:
    path:     /vue40
    defaults: { _controller: HomeBundle:Default:vue40 }

home_vue50:
    path:     /vue50
    defaults: { _controller: HomeBundle:Default:vue50 }

<<<<<<< HEAD
home_vue:
    path:     /vue
    defaults: { _controller: HomeBundle:Default:vue }

home_profile:
    path:     /profile
    defaults: { _controller: HomeBundle:Default:profile }
=======
home_vue60:
    path:     /vue60
    defaults: { _controller: HomeBundle:Default:vue60 }
>>>>>>> cc8c01a5ac7865aa363986046fed7088e9eb6b40
