home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Default:index }

home_vue10:
    path:     /vue10
    defaults: { _controller: HomeBundle:Default:vue10 }

home_vue20:
    path:     /vue20
    defaults: { _controller: HomeBundle:Default:vue20 }

home_vue30:
    path:     /vue30
    defaults: { _controller: HomeBundle:Default:vue30 }


home_vue40:
    path:     /vue40
    defaults: { _controller: HomeBundle:Default:vue40 }

home_vue50:
    path:     /vue50
    defaults: { _controller: HomeBundle:Default:vue50 }


home_profile:
    path:     /profile
    defaults: { _controller: HomeBundle:Default:profile }

home_vue60:
    path:     /vue60
    defaults: { _controller: HomeBundle:Default:vue60 }


rando10k1:
    path:     /rando10k1/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn }

rando10k1vue:
    path:     /rando10k1
    defaults: { _controller: HomeBundle:Rando:rando10k1 }

rando10k2:
    path:     /rando10k2/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn10k2 }

rando10k2vue:
    path:     /rando10k2
    defaults: { _controller: HomeBundle:Rando:rando10k2 }

rando50k1:
    path:     /rando50k1/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn50k1 }

rando50k1vue:
    path:     /rando50k1
    defaults: { _controller: HomeBundle:Rando:rando50k1 }

