home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Default:index }

home_vue:
    path:     /vue
    defaults: { _controller: HomeBundle:Default:vue }

home_profile:
    path:     /profile
    defaults: { _controller: HomeBundle:Default:profile }