home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Default:index }

home_vue10:
    path:     /vue10
    defaults: { _controller: HomeBundle:Default:vue10 }

home_vue20:
    path:     /vue20
    defaults: { _controller: HomeBundle:Default:vue20 }

home_vue30:
    path:     /vue30
    defaults: { _controller: HomeBundle:Default:vue30 }


home_vue40:
    path:     /vue40
    defaults: { _controller: HomeBundle:Default:vue40 }

home_vue50:
    path:     /vue50
    defaults: { _controller: HomeBundle:Default:vue50 }


home_profile:
    path:     /profile
    defaults: { _controller: HomeBundle:Default:profile }

home_vue60:
    path:     /vue60
    defaults: { _controller: HomeBundle:Default:vue60 }


rando10k1:
    path:     /rando10k1/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn }

rando10k1vue:
    path:     /rando10k1
    defaults: { _controller: HomeBundle:Rando:rando10k1 }

rando10k2:
    path:     /rando10k2/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn10k2 }

rando10k2vue:
    path:     /rando10k2
    defaults: { _controller: HomeBundle:Rando:rando10k2 }

rando50k1:
    path:     /rando50k1/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn50k1 }

rando50k1vue:
    path:     /rando50k1
    defaults: { _controller: HomeBundle:Rando:rando50k1 }

rando50k2:
    path:     /rando50k2/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn50k2 }

rando50k2vue:
    path:     /rando50k2
    defaults: { _controller: HomeBundle:Rando:rando50k2 }

rando50k3:
    path:     /rando50k3/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn50k3 }

rando50k3vue:
    path:     /rando50k3
    defaults: { _controller: HomeBundle:Rando:rando50k3 }

rando50k4:
    path:     /rando50k4/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn50k4 }

rando50k4vue:
    path:     /rando50k4
    defaults: { _controller: HomeBundle:Rando:rando50k4 }

rando60k1:
    path:     /rando60k1/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn60k1 }

rando60k1vue:
    path:     /rando60k1
    defaults: { _controller: HomeBundle:Rando:rando60k1 }

rando60k2:
    path:     /rando60k2/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn60k2 }

rando60k2vue:
    path:     /rando60k2
    defaults: { _controller: HomeBundle:Rando:rando60k2 }

rando60k3:
    path:     /rando60k3/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn60k3 }

rando60k3vue:
    path:     /rando60k3
    defaults: { _controller: HomeBundle:Rando:rando60k3 }

rando60k4:
    path:     /rando60k4/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn60k4 }

rando60k4vue:
    path:     /rando60k4
    defaults: { _controller: HomeBundle:Rando:rando60k4 }

