home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Default:index }

home_vue10:
    path:     /vue10
    defaults: { _controller: HomeBundle:Default:vue10 }

home_vue20:
    path:     /vue20
    defaults: { _controller: HomeBundle:Default:vue20 }

home_vue30:
    path:     /vue30
    defaults: { _controller: HomeBundle:Default:vue30 }


home_vue40:
    path:     /vue40
    defaults: { _controller: HomeBundle:Default:vue40 }

home_vue50:
    path:     /vue50
    defaults: { _controller: HomeBundle:Default:vue50 }


home_profile:
    path:     /profile
    defaults: { _controller: HomeBundle:Default:profile }

home_vue60:
    path:     /vue60
    defaults: { _controller: HomeBundle:Default:vue60 }


rando10k1:
    path:     /rando10k1/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn }

rando10k1vue:
    path:     /rando10k1
    defaults: { _controller: HomeBundle:Rando:rando10k1 }

rando10k2:
    path:     /rando10k2/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn10k2 }

rando10k2vue:
    path:     /rando10k2
    defaults: { _controller: HomeBundle:Rando:rando10k2 }


rando30k1:
    path:     /rando30k1/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn30k1 }

rando30k1vue:
    path:     /rando30k1
    defaults: { _controller: HomeBundle:Rando:rando30k1 }

rando30k2:
    path:     /rando30k2/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn30k2 }

rando30k2vue:
    path:     /rando30k2
    defaults: { _controller: HomeBundle:Rando:rando30k2 }

rando30k3:
    path:     /rando30k3/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn30k3 }

rando30k3vue:
    path:     /rando30k3
    defaults: { _controller: HomeBundle:Rando:rando30k3 }

rando30k4:
    path:     /rando30k4/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn30k4 }

rando30k4vue:
    path:     /rando30k4
    defaults: { _controller: HomeBundle:Rando:rando30k4 }

rando40k1:
    path:     /rando40k1/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn40k1 }

rando40k1vue:
    path:     /rando40k1
    defaults: { _controller: HomeBundle:Rando:rando40k1 }

rando40k2:
    path:     /rando40k2/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn40k2 }

rando40k2vue:
    path:     /rando40k2
    defaults: { _controller: HomeBundle:Rando:rando40k2 }

rando40k3:
    path:     /rando40k3/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn40k3 }

rando40k3vue:
    path:     /rando40k3
    defaults: { _controller: HomeBundle:Rando:rando40k3 }

rando40k4:
    path:     /rando40k4/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn40k4 }

rando40k4vue:
    path:     /rando40k4
    defaults: { _controller: HomeBundle:Rando:rando40k4 }


rando50k1:
    path:     /rando50k1/envoie
    defaults: {_controller: HomeBundle:Rando:modifybtn50k1 }

rando50k1vue:
    path:     /rando50k1
    defaults: { _controller: HomeBundle:Rando:rando50k1 }


